services:
  postgres:
    image: postgres:15
    container_name: wonga-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: WongaAssessmentDb
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: WongaAssessment.API/WongaAssessment.API/Dockerfile
    container_name: wongaassessment-api
    depends_on:
      - postgres
    restart: always
    ports:
      - "8080:80"